# Generated by Django 4.2.2 on 2023-07-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recurrence',
            field=models.CharField(choices=[('ONCE', 'O dată'), ('WEEKLY', 'Săptămânal'), ('MONTHLY', 'Lunar')], default='ONCE', max_length=10),
        ),
    ]
